In [ ]:
import pandas as pd

In [ ]:
shop_7sep={
    "Fruites":['Apple','Banana','Mango','Grapes'],
    "Price":[100,50,200,150],
    "Qunt":[5,10,15,20]
}
stock_7sep=pd.DataFrame(shop_7sep)
shop_8sep={
    "Fruites":['Apple','Banana','Mango','Grapes'],
    "Price":[150,50,250,190],
    "Qunt":[8,24,10,25]
}
stock_8sep=pd.DataFrame(shop_8sep)

#-------------------compare-----------------
stock_7sep.compare(stock_8sep)
stock_7sep.compare(stock_8sep,align_axis=0)
stock_7sep.compare(stock_8sep,keep_shape=True)
stock_7sep.compare(stock_8sep,keep_equal=True)
stock_7sep.compare(stock_8sep,align_axis=0,keep_shape=True,keep_equal=True)

### pivoting

In [ ]:
monthly_sales={
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":['Jan','Jan','Feb','Feb','Mar','Apr'],
    "Price":[95000,25000,67000,12000,65000,75000],
}
sales=pd.DataFrame(monthly_sales)
#----pivot----
sales.pivot(index='Product',columns='Month',values='Price')

In [14]:
monthly_sales={
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":['Jan','Jan','Feb','Feb','Mar','Mar'],
    "Price":[95000,25000,67000,12000,65000,75000],
}
sales=pd.DataFrame(monthly_sales)
#----pivot----
sales.pivot_table(index="Product",columns="Month",values="Price",aggfunc="sum")

Month        Feb      Jan       Mar
Product
Laptop   67000.0  95000.0  140000.0
Mobile   12000.0  25000.0       NaN

### Melting

In [18]:
shop_sales={
    "Product":['Laptop','Mobile','Mouse'],
    "Jan":[95000,25000,150],
    "Feb":[67000,12000,200],
    "Mar":[65000,75000,250]
}
sales_df=pd.DataFrame(shop_sales)
sales_df.melt(id_vars="Product",var_name="Month",value_name="Price")

  Product Month  Price
0  Laptop   Jan  95000
1  Mobile   Jan  25000
2   Mouse   Jan    150
3  Laptop   Feb  67000
4  Mobile   Feb  12000
5   Mouse   Feb    200
6  Laptop   Mar  65000
7  Mobile   Mar  75000
8   Mouse   Mar    250